### ISSUE TITLE
Odd formula for determining floor tile's color

### ISSUE THREAD

**Issue by fdiniello-nobleo** [nobleans-playground/coding-challenge-colour-battle#6]
In the file: 
https://github.com/nobleans-playground/coding-challenge-colour-battle/blob/master/world.py#L66

When you are trying to determine the new tile's color the formula isn't working properly. I don't understand what's is supposed to be doing, but the fact the bot's ID comes into play is really odd.
I found out that if I have a "low" value, i can NEVER win over a bot that has a higher value.

**Comment by heinwessels** [comment]
The important to rememberthat the ID's are randomized every new game. That means on average everybody is equal. Some games you might have a disadvantage, but other games you will have the advantage.

Here you can see `your_id` vs `enemy_id`, that over average it evens out, as long as we play enough games, and the final tournament will consists a few 10 thousand games, where every time each game all IDs are randomized.
```
0 vs. 0 -> 0
0 vs. 1 -> 2
0 vs. 2 -> 1
1 vs. 0 -> 1
1 vs. 1 -> 0
1 vs. 2 -> 2
2 vs. 0 -> 2
2 vs. 1 -> 1
2 vs. 2 -> 0
```
https://godbolt.org/z/W8bGq33EP


You can see the IDs changing by clicking on the `Id#` button in the GUI, and then clicking `Reset`
